name: Using environment variables in Actions

on: [push]

env:
    GLOBALENV: Available for all jobs in this workflow

jobs:
    sample-job-1:
        runs-on: ubuntu-latest
        env:
          JOBENV: Available for all jobs in this workflow
        steps:
            - name: step-1
              run: echo "${GLOBALENV}"

            - name: step-2
              run: echo "${JOBENV}"

    sample-job-2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${GLOBALENV}"
